### ISSUE TITLE
Correct handling of paths when `basePath` is set in Swagger definition

### ISSUE THREAD

**Issue by philgs** [APIDevTools/swagger-express-middleware#13]
In my Swagger 2.0 definition, I have

``` yaml
basePath: /api

paths:
  /spinners:
    get: ...
  /spinners/{id}
    parameters: ...
    get: ...
```

When I do `GET http://localhost:3000/api/spinners/0`, I receive a 404. 

If I comment out the `basePath` line in the definition, then do `GET http://localhost:3000/spinners/0`, I get the JSON data for the object (as I've set it in the mocks and datastore).

Based on the debug output, it is parsing the path correctly. However, when it calls `get` on the datastore, it seems to be passing the full path, `/api/spinners/0` as the `resource` parameter to `DataStore.get`, instead of removing the base path first.

This is in version 0.4.7, which is the most recent in NPM.
