### ISSUE TITLE
Parsing array in req.body fails for date-time values

### ISSUE THREAD

**Issue by Steffen911** [APIDevTools/swagger-express-middleware#133]
**What happened**:
My body contains an array of objects that contain date-time strings. When I try to parse a valid body with the parseRequest() middleware an exception is thrown saying `Invalid type: object (expected string)`.

I assume that this is related to the validation that happens _after_ parsing: https://github.com/APIDevTools/swagger-express-middleware/blob/master/lib/helpers/json-schema.js#L434

The date-time is converted into a Date object and, therefore, is not a string anymore. Hence, the second validation fails with the above statement.

**What I expect to happen**:
The validation should succeed.

**Example**:
spec:
```yaml
parameters:
  - in: body
    name: body
    schema:
      type: array
      items:
        type: object
        properties:
          startDate:
            type: string
            format: date-time
```

body:
```json
[{
  "startDate": "2018-03-23T04:11:21Z"
}]
```
