### ISSUE TITLE
Add data type null

### ISSUE THREAD

**Issue by fredtma** [APIDevTools/swagger-express-middleware#146]
Hi,

I currently have a property with a data type: ['null', array]
in the file, lib/helpers/json-schema.js would be great to add the dataType null

let dataTypes = ["string", "number", "integer", "boolean", "array", "object", "file", "null"];

**Comment by JamesMessinger** [comment]
The Swagger spec doesn't allow multiple types.  So you should just use `type: array`.  In addition, Swagger 2.0 doesn't have any built-in support for `null` values.  Many people use `x-nullable: true` for this instead.  Support for `null` values was added in OpenAPI 3.0 via `nullable: true`.

**Comment by t0lik** [comment]
@JamesMessinger Can you please show an example how to describe a schema in YAML with `x-nullable: true`? Does swagger-express-middleware support it?

**Comment by JamesMessinger** [comment]
@t0lik in OpenAPI 2.0 (aka "Swagger") you can add custom [specification extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#specification-extensions) anywhere you want.  These can be anything you want, as long as they start with `x-`.  A common practice is to use `x-nullable` to indicate whether a field is nullable or not.  Like this:

```yaml
title: Person
type: object
properties:
  firstName:
    type: string
    x-nullable: false
  lastName:
    type: string
    x-nullable: true
```

Note that this *is not necessary* in OpenAPI 3.0, since it includes an official `nullable` property.  So you can change the above example to this instead:

```yaml
title: Person
type: object
properties:
  firstName:
    type: string
    nullable: false
  lastName:
    type: string
    nullable: true
```

In the **next version** of OpenAPI (3.1), it will support `null` as a type, and the `type` property can be an array of types, so neither `nullable` nor `x-nullable` will be necessary anymore.  Instead, you'll just be able to do this:

```yaml
title: Person
type: object
properties:
  firstName:
    type: string
  lastName:
    type: 
      - string
      - null
```
