### ISSUE TITLE
JSON schema validation error for array of single string in body

### ISSUE THREAD

**Issue by roryhow** [APIDevTools/swagger-express-middleware#147]
I have a swaggerfile that is roughly as follows:

```yaml
  /multiple:
    delete:
      operationId: deleteMultipleItems
      description: Delete multiple items
      parameters:
        - name: ids
          in: body
          schema:
            type: array
            items:
              type: string
```

Here, the ID's that we are looking to delete are always 6-digit strings (i.e `000000` is a valid entry, as is something that would also be a valid number, such as `999999`). However, if I make a request that looks as follows:

```
DELETE .../multiple
content-type: application/json

[ "999999" ]
```

I receive a validation error that looks as follows:

```json
...
"code": "INVALID_REQUEST_PARAMETER",
      "errors": [
        {
          "code": "INVALID_TYPE",
          "params": [
            "array",
            "integer"
          ],
          "message": "Expected type array but found type integer",
          "path": []
        }
      ],
...
```

However, if I supply multiple values (`["999999", "999998"]`), the validation passes successfully. It seems that for a single value, the value is being coerced into a number, and then from an array to a primitive. This then causes the validation to fail.

Is this a bug with the validation, or is there something else that I should be doing in order to get around this?

Thanks for your help!
