### ISSUE TITLE
Is there a simple way to override the automatic primary key detection?

### ISSUE THREAD

**Issue by Akuryou** [APIDevTools/swagger-express-middleware#15]
Hi,

I stumbled over your project today and really like it! Good work!

I just got one issue I can't get to work.
I got a nested data structure like: A > B
Both A and B got an attribute called "Oid" as primary key and also a 'name' attribute.
So it is supposed to look like:
/A/{Oid}/B/{Oid}

But since 'Oid' is not in the auto lookup list (https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#how-primary-keys-are-determined) the mock middleware pics 'name'

Is there a simple(!) way to specify the PK of a resource?

**Comment by BigstickCarpet** [comment]
Yeah, I've been trying to think of an elegant way to allow people to specify custom "ID" fields for their resources, specifically because of reasons like this.

One idea is to use [vendor extensions](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#vendorExtensions), which would look something like this:

```yaml
definitions:
  person:
    type: object
    x-primary-key: Oid       # <---- vendor extension
    properties:
      Oid:
        type: number
      Name:
        type: string
```

Another idea is to make it an option on the [mock middleware](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md), which would look something like this:

```javascript
app.use(middleware.mock({
  primaryKeyNames: ['Oid', 'SomeOtherId', 'YetAnotherId']
}));
```

Another option is to use [the `rel` keyword from JSON Hyper-Schema](https://tools.ietf.org/html/draft-luff-json-hyper-schema-00#section-5.2).  This has the advantage of being based on a standard, rather than something I just made-up.  But it has the disadvantage of being _very_ verbose and complicated:

```yaml
definitions:
  person:
    type: object
    properties:
      Oid:
        type: number
      Name:
        type: string
    links:
      - rel: self                 # <--- Defines this as the identifying href
        href: "/people/{Oid}"     # <--- Defines "Oid" as the identifying property
```
